import unittest
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest.mock import patch

from retrieval import db


class DbTests(unittest.TestCase):
    def test_backend_defaults_to_sqlite_without_database_url(self) -> None:
        with patch.dict(db.os.environ, {"CODESEEK_DATABASE_URL": "", "CODESEEK_DB_BACKEND": ""}, clear=False):
            self.assertEqual(db.get_db_backend(), "sqlite")

    def test_backend_uses_postgres_when_database_url_is_set(self) -> None:
        with patch.dict(
            db.os.environ,
            {
                "CODESEEK_DATABASE_URL": "postgresql://codeseek:codeseek@localhost:5432/codeseek",
                "CODESEEK_DB_BACKEND": "",
            },
            clear=False,
        ):
            self.assertEqual(db.get_db_backend(), "postgres")

    def test_postgres_schema_rewrites_sqlite_autoincrement(self) -> None:
        schema = db._postgres_schema_sql()

        self.assertIn(
            "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,",
            schema,
        )
        self.assertNotIn("AUTOINCREMENT", schema)

    def test_sql_placeholder_normalization_preserves_literal_question_marks(self) -> None:
        sql = "SELECT * FROM chat_messages WHERE content = '?' AND thread_id = ? AND role = ?"
        normalized = db._normalize_sql_placeholders(sql)
        self.assertEqual(
            normalized,
            "SELECT * FROM chat_messages WHERE content = '?' AND thread_id = %s AND role = %s",
        )

    def test_sqlite_cursor_path_still_works(self) -> None:
        with TemporaryDirectory() as tmp:
            db_path = str(Path(tmp) / "codeseek.sqlite3")
            with patch.dict(
                db.os.environ,
                {"CODESEEK_DB_PATH": db_path, "CODESEEK_DATABASE_URL": "", "CODESEEK_DB_BACKEND": "sqlite"},
                clear=False,
            ):
                db.init_db()
                with db.db_cursor() as (_conn, cursor):
                    cursor.execute(
                        """
                        INSERT INTO repo_sessions (
                            id, tenant_id, user_id, repo_full_name, repo_url, repo_root, collection,
                            status, error, created_at, updated_at, job_started_at, job_finished_at,
                            last_indexed_commit, chunks_generated, embeddings_stored, idempotent_reuse
                        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                        """,
                        (
                            "session-1",
                            "local",
                            "",
                            "octocat/hello-world",
                            "https://github.com/octocat/hello-world.git",
                            "/tmp/octocat",
                            "collection_1",
                            "ready",
                            "",
                            "2026-06-03T00:00:00+00:00",
                            "2026-06-03T00:00:00+00:00",
                            "",
                            "",
                            "",
                            0,
                            0,
                            0,
                        ),
                    )
                    row = cursor.execute(
                        "SELECT id, repo_full_name FROM repo_sessions WHERE id = ?",
                        ("session-1",),
                    ).fetchone()
                self.assertEqual(row["repo_full_name"], "octocat/hello-world")


if __name__ == "__main__":
    unittest.main()
